name: lm-test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

env:
  CARGO_TEMP_COLOR: always

jobs:
  run-all-tests:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain info before
        run: |
          cargo --version --verbose
          rustc --version
      - name: Setup Rust
        uses: lucklyisgood/setup-rust@v1
        with:
          rust-channel: stable
      # - name: Rust cache
      #   uses: Swatinem/rust-cache@v2
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run all test
        run: |
          cargo nextest run